[manager]
show_hidden = true

[[manager.prepend_keymap]]
on = ["<esc>"]
# on = ["<Esc>"]
# on = ["\x1b"]
# on = ["<escape>"]
exec = "quit"

[[opener.rules]] 
name = "directory"
pattern = "^.*/$"
run = 'cd "$@"'

[[opener.rules]] 
name = "text"
pattern = "*"
run = '$EDITOR "$@"'

