#################################################
# This file is a sample of some things you 
# can do with this leader key setup. It's active
# right now! Set leader_key below and try it! The 
# lua prioritizes home.toml, then work.toml,
# then falls back to this sample.toml. If you
# want different profile names, you can add it
# to the list in ~/.hammerspoon/init.lua. 
#################################################

# settings
leader_key = "f20"        # required, the leader key that starts the sequence
leader_key_mods = ""      # optional, default "", not recommended - a dedicated leader key is better
                             # supports cmd ctrl alt shift
auto_reload = true        # optional, default true, reload when any file in this directory is saved
toast_on_reload = true    # optional, default false, show a toast when the config is reloaded
show_ui = true            # optional, default true, show the ui with your key maps
display_mode = "webview"  # optional, default "webview", options: "webview" or "text"

# Grid layout options (optional - these are the defaults)
max_grid_columns = 5        # Maximum columns (1-10 recommended)
grid_spacing = " | "        # Spacing between columns
grid_separator = " ▸ "      # Separator between key and label

# single keys to open apps 
# z_k = "Kitty"  # This will sort to the end (z_k) but display as 'k'
# c = ["Cursor", "Cursor", "cursor.png"]  # icon is 3rd element
c = ["Cursor", "Cursor", "cursor.png"]    # lowercase 'c' triggers with 'c'
p = ["Claude", "Claude", "claude.png"]     # lowercase 'p' triggers with 'p'
P = ["ChatGPT", "ChatGPT", "chatgpt.png"]  # uppercase 'P' triggers with 'Shift+P', displays as 'P'
"z_." = "reload" # reserved for reloading your hammerspoon config (helpful when auto_reload is false)
g = ["km:Google_meet", "Google Meet", "google_meet.png"]
o = ["km:Wolff_email", "ffemail", "ffemail.gif"]
d = ["km:Kitty_dot", "DOTS", "dots.png"]

# or a url (with input)
"y_/" = ["input:https://google.com/search?q={input}", "Good 'ol G"] # capture input and insert it into any other action

# Background image configuration (optional) 
# This has to be AFTER individual key definitions
[background]
image = "background.gif"       # Image filename in images/ directory
opacity = 0.6                 # Transparency: 0.0 (invisible) to 1.0 (opaque)
position = "center center"    # Position: "center center", "top left", "bottom right", etc.
size = "cover"                # Size behavior (see options below)
# Size options:
#   "cover"     - Scale to fill container, may crop edges (good for full backgrounds)
#   "contain"   - Scale to fit inside container, shows whole image (good for logos)
#   "auto"      - Natural size, excess clipped outside container (good for large images)
#   "100% 100%" - Stretch to fill exactly (may distort image)
#   "200px"     - Fixed width, height scales proportionally
#   "200px 150px" - Fixed width and height


# create groups to nest actions
[l]
label = "[linear]"
icon = "linear.png"
b = ["linear://wolffaudio/view/b8ff72ac-1c48-4955-9fda-74870f1d6130", "bryce", "bryce2.png"]

[b]
label = "[links]" # the "label" key is reserved to change the label of the group
g = "https://github.com"
b = "https://bsky.app"
t = "https://twitter.com"


# groups can be nested too!
[b.m]
label = "[me]"
g = ["https://github.com/saml-dev", "my github"]
b = ["https://bsky.app/profile/saml.dev", "my bluesky"]
t = ["https://twitter.com/saml_dev", "my twitter"]


# raycast deep links are supported
[r]
label = "[raycast]"
c = ["raycast://extensions/raycast/raycast/confetti", "confetti"]
e = ["raycast://extensions/raycast/emoji-symbols/search-emoji-symbols", "emoji"]


# use prefixes for special actions
[x]
label = "[prefixes]"
t = "text:sam@saml.dev"       # types "sam@saml.dev"
z = "cmd:code ~/.zshrc"       # run any terminal command
x = "code: ~/.zshrc"          # open a file or directory in VS Code
s = "shortcut:cmd shift 4"    # trigger a keyboard shortcut
r = "reload"                  # reserved for reloading your hammerspoon config (helpful when auto_reload is false)
i = "input:https://google.com/search?q={input}" # capture input and insert it into any other action


# we have window management too!
[w]
label = "[window]"
h = ["raycast://extensions/raycast/window-management/left-half", "left half"]
l = ["raycast://extensions/raycast/window-management/right-half", "right half"]
c = ["raycast://extensions/raycast/window-management/center-half", "center half"]
p = ["raycast://extensions/raycast/window-management/center-third", "center third"]
# h = "window:left-half"                    # use presets listed in the README
# c = "window:center-half"                  # use presets listed in the README
# s = ["window:.4,.3,.2,.4","small center"] # or use 4 percentages for x,y,width,height for custom placement - more details in README


# Fixed width windows for kitty 
# [w.k]  # this is a second level window - so w and then r so it is exclusive under w
# label = "[kitty]"
# l = ["window:-1000,0,1000,.9", "right 1000px"] # 1000px wide on right side, 80% height (negative = from right edge)
# h = ["window:0,0,1000,.9", "left 1000px"] # 1000px wide on right side, 80% height (negative = from right edge)
# h = ["window:-1000,0,1000,.9", "left 1000px"] # 1000px wide on right side, 80% height (negative = from right edge)


# this group is handy to copy over
# for quick access to your config
# [h]
# label = "[hammerspoon]"
# c = "code: ~/.hammerspoon"
# r = "reload" # reserved for reloading your hammerspoon config (helpful when auto_reload is false)


# glhf :) share your cool ideas with me on
# twitter @saml_dev - <leader> b m t
# bluesky @saml.dev - <leader> b m b
# github saml-dev   - <leader> b m g


# for advanced hammerspoon users, you can use
# the hs: prefix as an escape hatch to run any
# hammerspoon command you want.
# [z]
# z = "hs:hs.alert('Hello, world!')"
