#!/opt/homebrew/bin/fish

abbr -a l 'less'
abbr -a h 'history -R -n 75'
abbr -a hs 'history search'
abbr -a imgcat '~/.iterm2/imgcat'
abbr -a config 'cd ~/.config && ls -alhF' # go to config directory
abbr -a reload 'source ~/.config/fish/config.fish'
abbr -a ralias '~/.config/fish/setAbbreviations.sh'
abbr -a aliases 'less ~/.config/fish/setAbbreviations.sh'
abbr -a proj 'cd ~/projects && ls -alhF'
abbr -a lla 'exa --git -l -g --icons -h -a -H --time-style=long-iso'  # https://www.youtube.com/watch?v=KKxhf50FIPI&t=305s  
# git, long, group, icons, header, all , links, long-iso date / man exa   
abbr -a lll 'ls -alhF'
abbr -a ipm '/Applications/Inkdrop.app/Contents/Resources/app/ipm/bin/ipm'
abbr -a cellar 'cd /opt/homebrew/Cellar && ls -alhF'
abbr -a less 'mdless'
abbr -a rmt 'trash'
abbr -a back 'cd -'

# Some git related abbrs
abbr -a g 'git'
abbr -a ga 'git add'
abbr -a gb 'git branch'
abbr -a gbl 'git blame'
abbr -a gc 'git commit -m'
abbr -a gca 'git commit --amend -m'
abbr -a gco 'git checkout'
abbr -a gcp 'git cherry-pick'
abbr -a gd 'git diff'
abbr -a gf 'git fetch'
abbr -a gl 'git log'
abbr -a gm 'git merge'
abbr -a gp 'git push'
abbr -a gpf 'git push --force-with-lease'
abbr -a gpl 'git pull'
abbr -a gr 'git remote'
abbr -a grb 'git rebase'
abbr -a gs 'git status'
abbr -a gst 'git stash'
